spring:
  application:
    name: classroom-monitoria
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/store}
    username: ${DATABASE_USERNAME:store}
    password: ${DATABASE_PASSWORD:store123321}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: monitoria
  jpa:
    properties:
      hibernate:
        default_schema: monitoria
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

springdoc:
  api-docs:
    path: /monitorias/v3/api-docs
  swagger-ui:
    path: /monitorias/swagger-ui.html


management:
  endpoints:
    web:
      base-path: /monitorias/actuator
      exposure:
        include: [ 'prometheus' ]

eureka: 
  client:
    reguster-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}


